### ISSUE TITLE
activity user error while comparing a member with 0 msgs

### ISSUE THREAD

**Issue by Rajdave69** [Some-Random-Guys/Analytics-Package#5]
Comparing x number of members, while one has 0 messages for that timeperiod and the other than <1 cause an error

```py
x and y must have same first dimension, but have shapes (7,) and (8,)
2023-07-04 13:23:06 ERROR    discord.app_commands.tree Ignoring exception in command 'user'
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/discord/app_commands/commands.py", line 841, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/cogs/Activity.py", line 169, in activity_user
    await interation.followup.send(embed=embed, file=discord.File(e, filename="activity.png"))
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/file.py", line 97, in __init__
    self.fp = open(fp, 'rb')
              ^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/home/container/.local/lib/python3.11/site-packages/discord/app_commands/commands.py", line 867, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/app_commands/commands.py", line 856, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'user' raised an exception: TypeError: expected str, bytes or os.PathLike object, not NoneType
```

perhaps error is related to the fill-in system

**Comment by Rajdave69** [comment]
fixed for 1w and 2w
